kind: Service
apiVersion: v1
metadata:
  name: producer
  labels:
    app: dotnet
spec:
  selector:
    app: dotnet
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  labels:
    app: dotnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet
  template:
    metadata:
      labels:
        app: dotnet
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "producer"
        dapr.io/port: "3000"
    spec:
      containers:
      - name: dotnet
        image: youngp/producer:latest
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
